name: Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install Dependencies
      run: bundle install

    - name: Run Tests
      run: |
        rake spec
        rake cucumber
        
    - uses: actions/checkout@v1
  
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 7a7d31601043cd7fb9ba2909f44fe341bbfd7c89c16af2aae25792bb97e36f48
      with:
        coverageCommand: rake cucumber